### PR TITLE
Added rate limiter for the Slack API

### PR DESCRIPTION
**Pull request by janovesk**
Slack has [rate limits](https://api.slack.com/docs/rate-limits). This introduces a rate limiter to make sure the bot will not break them when too many sends are done in rapid succession.

### CODE REVIEW

**Comment by distantcam** [comment]
I've got a couple of issues with this implementation.

- So you've basically got a Thread Sleep between sending messages to the socket. What if the socket dies between messages?
- What if someone else sends a command to pbot while it's processing it's message queue? Does that command get blocked trying to send a response?

**Comment by janovesk** [comment]
No, there is a thread sleep IF the current request would exceeding the send limit, not between every send to the socket. Not seeing how this is changing anything related to how a socket dies.

If someone else sends a command and need a reply they have to wait if the bot is above the rate limit, just like every other send. The rate limit is for the slack commuication from the bot as a whole, not just your command.

**Comment by distantcam** [comment]
Sorry, yes, there's only a thread sleep if there's been less than 1 second between messages.

What I meant about the socket dying is that multiple messages can be sent to the adapter at once. The adapter checks the socket, makes sure the bot is in the room, and then sends all the messages to the API, which forwards them to the socket. Now because there's a delay the socket may close while the messages are being sent. But the socket may close during the sleep delay, so then the next send may fail, causing an exception.

**Comment by janovesk** [comment]
Is that any different from what is currently happening? The socket may still die between those messages without the sleep?

**Comment by distantcam** [comment]
The main difference is now, for 10 messages the chances of the socket closing over the milliseconds it takes to send those messages is low, but the chances of the socket closing over 10 seconds is greater.

**Comment by janovesk** [comment]
Ok, that's fair enough if we know that sockets getting closed is a problem. Isn't SlackAdapter.SocketOnClose supposed to reconnect that closed socket anyway? I see it's called async, so it might not have reconnected?

**Comment by distantcam** [comment]
Like everything with the slack api, there's limits. :P The reconnect mechanism in the socket close retries every second for 10 seconds, then waits 1 minute before trying again 10 times every second. So the socket can remain closed for a minute if the 10 seconds of retries fails.

**Pull request merged**
